version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
    env_file:
      - .env
    volumes:
      - .:/work
    ports:
      - "3000:3000"